{{/*
Template file: templates/oai-nr-ues.yaml
This template replaces your individual UE templates with a dynamic generator
*/}}

{{- if .Values.oai-nr-ues.enabled }}
{{- range $index := until (.Values.oai-nr-ues.count | int) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%02d-configmap" $.Values.oai-nr-ues.namePrefix $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: oai-nr-ue
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: nr-ue
    ue-index: {{ $index | quote }}
data:
  config.yaml: |
    timeZone: {{ $.Values.oai-nr-ues.template.config.timeZone | quote }}
    rfSimServer: {{ $.Values.oai-nr-ues.template.config.rfSimServer | quote }}
    fullImsi: {{ printf "%s%03d" $.Values.oai-nr-ues.imsiBase (add $.Values.oai-nr-ues.imsiStartIndex $index) | quote }}
    fullKey: {{ $.Values.oai-nr-ues.template.config.fullKey | quote }}
    opc: {{ $.Values.oai-nr-ues.template.config.opc | quote }}
    dnn: {{ $.Values.oai-nr-ues.template.config.dnn | quote }}
    sst: {{ $.Values.oai-nr-ues.template.config.sst | quote }}
    sd: {{ $.Values.oai-nr-ues.template.config.sd | quote }}
    usrp: {{ $.Values.oai-nr-ues.template.config.usrp | quote }}
    useAdditionalOptions: {{ $.Values.oai-nr-ues.template.config.useAdditionalOptions | quote }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%02d" $.Values.oai-nr-ues.namePrefix $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: oai-nr-ue
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: nr-ue
    ue-index: {{ $index | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oai-nr-ue
      app.kubernetes.io/instance: {{ $.Release.Name }}
      ue-index: {{ $index | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oai-nr-ue
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: nr-ue
        ue-index: {{ $index | quote }}
    spec:
      containers:
      - name: nr-ue
        image: {{ printf "%s:%s" $.Values.oai-nr-ues.template.nfimage.repository $.Values.oai-nr-ues.template.nfimage.version }}
        imagePullPolicy: {{ $.Values.oai-nr-ues.template.nfimage.pullPolicy }}
        
        env:
        - name: UE_NAME
          value: {{ printf "%s-%02d" $.Values.oai-nr-ues.namePrefix $index | quote }}
        - name: UE_INDEX
          value: {{ $index | quote }}
        
        {{- if $.Values.oai-nr-ues.template.resources.define }}
        resources:
          {{- if $.Values.oai-nr-ues.template.resources.limits }}
          limits:
            {{- if $.Values.oai-nr-ues.template.resources.limits.nf.cpu }}
            cpu: {{ $.Values.oai-nr-ues.template.resources.limits.nf.cpu }}
            {{- end }}
            {{- if $.Values.oai-nr-ues.template.resources.limits.nf.memory }}
            memory: {{ $.Values.oai-nr-ues.template.resources.limits.nf.memory }}
            {{- end }}
          {{- end }}
          {{- if $.Values.oai-nr-ues.template.resources.requests }}
          requests:
            {{- if $.Values.oai-nr-ues.template.resources.requests.nf.cpu }}
            cpu: {{ $.Values.oai-nr-ues.template.resources.requests.nf.cpu }}
            {{- end }}
            {{- if $.Values.oai-nr-ues.template.resources.requests.nf.memory }}
            memory: {{ $.Values.oai-nr-ues.template.resources.requests.nf.memory }}
            {{- end }}
          {{- end }}
        {{- end }}
        
        volumeMounts:
        - name: config-volume
          mountPath: /opt/oai-nr-ue/etc
          
      volumes:
      - name: config-volume
        configMap:
          name: {{ printf "%s-%02d-configmap" $.Values.oai-nr-ues.namePrefix $index }}
          
      {{- if $.Values.oai-nr-ues.template.nodeSelector }}
      nodeSelector:
        {{- toYaml $.Values.oai-nr-ues.template.nodeSelector | nindent 8 }}
      {{- end }}
      
      {{- if $.Values.global.waitForRadio }}
      initContainers:
      - name: wait-for-radio
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z {{ $.Values.oai-nr-ues.template.config.rfSimServer }} 4043; do echo waiting for radio; sleep 2; done;']
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%02d-service" $.Values.oai-nr-ues.namePrefix $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: oai-nr-ue
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: nr-ue
    ue-index: {{ $index | quote }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oai-nr-ue
    app.kubernetes.io/instance: {{ $.Release.Name }}
    ue-index: {{ $index | quote }}
  ports:
  - name: oai-nr-ue
    port: 80
    targetPort: 80
    protocol: TCP

{{- end }}
{{- end }}
